# Generated by Django 5.2.1 on 2026-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(default=1, upload_to='seller_profile'),
            preserve_default=False,
        ),
    ]
