# Generated by Django 5.2.1 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_seller_bio_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
