# Generated by Django 5.2.1 on 2026-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_alter_seller_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profile'),
        ),
    ]
