# Generated by Django 5.2.1 on 2026-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_alter_seller_bio_alter_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
