# Generated by Django 5.2.1 on 2026-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_seller_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_backgrounds/'),
        ),
    ]
