# Generated by Django 5.2.1 on 2026-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_seller_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
