# Generated by Django 5.2.1 on 2026-04-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automotive',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='beauty',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='books',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='groceries',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='health',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='home',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='kids',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='user_relation',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='user_relation',
        ),
        migrations.AddField(
            model_name='automotive',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='beauty',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='books',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='comment',
            name='seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='groceries',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='health',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='home',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='kids',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='order_product',
            name='seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='pets',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='sports',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='tools',
            name='Seller_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.seller'),
        ),
    ]
