# Generated by Django 5.2.1 on 2026-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_automotive_user_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
