# Generated by Django 5.2.1 on 2026-05-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automotive',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='beauty',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='footwear',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='groceries',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='kids',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='Seller_relation',
            new_name='seller_relation',
        ),
    ]
