# Generated by Django 5.2.1 on 2026-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_seller_relation_automotive_seller_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
