# Generated by Django 5.2.1 on 2026-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_comment_is_reported_comment_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
