# Generated by Django 5.2.1 on 2026-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_automotive_price_alter_beauty_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
